---
title: 'SmallHD: On-Camera Field Monitors for the Creative Video Professional'
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: 
description: ''
baseurl: ''
url: ''
twitter_username: 
github_username: 
markdown: kramdown
